# Generated by Django 5.1.2 on 2024-11-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
