# Generated by Django 5.1.2 on 2024-11-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_page_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemmetric',
            name='unit',
            field=models.CharField(default='', max_length=20),
        ),
    ]
