# Generated by Django 5.1.2 on 2024-11-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_systemmetric_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemmetric',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
