# Generated by Django 5.1.2 on 2024-11-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0004_alter_systemmetric_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
